# Generated by Django 3.1.2 on 2020-11-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
