# Generated by Django 3.1.2 on 2020-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NewsApp', '0002_delete_siteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
